# Generated by Django 4.2.1 on 2023-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
