# Generated by Django 4.2.1 on 2023-06-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
