# Generated by Django 4.2.1 on 2023-05-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='BookingSystem.flight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='BookingSystem.passenger'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane', to='BookingSystem.plane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='BookingSystem.route'),
        ),
    ]
