# Generated by Django 4.2.1 on 2023-05-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0002_alter_bookings_flight_alter_bookings_passenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='time_Zone',
            new_name='time_zone',
        ),
    ]
