# Generated by Django 4.2.1 on 2023-05-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0004_alter_route_stopover_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='depature_location',
            new_name='departure_location',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='depature_time',
            new_name='departure_time',
        ),
    ]
